name: Build Linux

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.19"
          - "1.20"
          - "1.21"
          - "stable"

    runs-on: ubuntu-latest

    steps:
      - name: Library dependencies
        run: sudo apt-get install libmpv-dev libglx-dev libgl-dev
      - uses: actions/checkout@v4
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Get Go deps
        run: go get .
      - name: Compile
        run: go build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.go == 'stable' && startsWith(github.ref, 'refs/tags/')
        with:
          files: stmp-linux-x86_64
