name: Build macOS

on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.21"]

    runs-on: macos-latest

    steps:
      - name: Library dependencies
        run: brew install mpv

      - uses: actions/checkout@v4

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Compile
        run: |
          go get .
          go build .
