name: Build Linux

on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.19", "1.20", "1.21"]

    runs-on: ubuntu-latest

    steps:
      - name: Library dependencies
        run: sudo apt-get install libmpv-dev libgl1

      - uses: actions/checkout@v4

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Compile
        run: |
          go get .
          go build .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.go == '1.21' && startsWith(github.ref, 'refs/tags/')
        with:
          files: stmp
