name: Build macOS

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.21"]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Library dependencies
        run: brew install mpv

      - name: Setup path
        run: |
          export C_INCLUDE_PATH="$(brew --prefix)/include:$C_INCLUDE_PATH"
          export LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH"

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Compile
        run: |
          go build
