name: Build macOS x86_64

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go:
          - "1.21"
          - "1.22"

    runs-on: macos-13

    steps:
      - name: Library dependencies
        run: brew install mpv

      - uses: actions/checkout@v4

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Get Go deps
        run: go get .

      - name: Export paths
        uses: spezifisch/export-homebrew-build-paths@v0.1.1

      - name: Compile
        run: go build
