name: Build binaries

on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Library dependencies
        run: sudo apt-get install libmpv-dev libglx-dev libgl-dev

      - name: Compile
        run: |
          go get .
          go build .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: stmp
