name: golangci-lint on macOS

on: [push]

permissions:
  contents: read

# do a separate lint job on macOS to catch platform-dependent problems
jobs:
  golangci:
    name: Lint macOS
    runs-on: macos-latest

    steps:
      - name: Library dependencies
        run: brew install mpv

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Export paths
        run: |
          echo "export C_INCLUDE_PATH=/usr/local/include:/opt/homebrew/include:$C_INCLUDE_PATH" >> $GITHUB_ENV
          echo "export LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "export CGO_CFLAGS=\"-I/usr/local/include -I/opt/homebrew/include\"" >> $GITHUB_ENV
          echo "export CGO_LDFLAGS=\"-L/usr/local/lib -L/opt/homebrew/lib\"" >> $GITHUB_ENV

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          skip-cache: true
