name: markdownlint

on:
  push:
    paths-ignore:
      - "*.md"

permissions:
  contents: read

jobs:
  md:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
