name: golangci-lint

on: [push]

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Library dependencies
        run: sudo apt-get install libmpv-dev libglx-dev libgl-dev

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
